version: 0.2

env:
  variables:
      IMAGE_REPO_NAME: "ci-tester"
      IMAGE_TAG: "1.0.0"
      AWS_DEFAULT_REGION: "YOUR_REGION"
      AWS_ACCOUNT_ID: "YOUR_ACCOUNT_ID"
phases:
  pre_build:
    commands:
      - echo Staring Docker Daemon
      - service docker start
      - sleep 1
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the War File
      - cd ci-tester
      - mvn clean && mvn package
      - echo Building the Docker Image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build Completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - ci-tester-0.1.0.war
  discard-paths: yes
  base-directory: ci-tester/target